import {
  AlertCircle,
  BarChart,
  Book,
  BookOpen,
  Calendar,
  Circle,
  Clock,
  Flame,
  Globe,
  Handshake,
  Home,
  Mic,
  MessageCircle,
  PenLine,
  Shield,
  Smile,
  Sprout,
  Star,
  Target,
  Tent,
  User,
  Users,
  Video,
  Zap,
  Volume2,
  PlayCircle,
  MessageSquare,
  Smartphone,
  Heart,
  Recycle,
  Gift,
  SquareCheckBig,
  Repeat,
  Lightbulb,
  ShieldCheck,
  CheckCircle,
  Brain,
  Award,
} from "lucide-react";

export const ICONS = {
  "alert-circle": AlertCircle,
  award: Award,
  "bar-chart": BarChart,
  book: Book,
  "book-open": BookOpen,
  brain: Brain,
  calendar: Calendar,
  "check-circle": CheckCircle,
  circle: Circle,

  clock: Clock,
  flame: Flame,
  gift: Gift,
  globe: Globe,
  handshake: Handshake,
  heart: Heart,
  home: Home,
  lightbulb: Lightbulb,
  mic: Mic,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  "pen-line": PenLine,
  "play-circle": PlayCircle,
  recycle: Recycle,
  repeat: Repeat,
  shield: Shield,
  "shield-check": ShieldCheck,
  smartphone: Smartphone,
  smile: Smile,
  sprout: Sprout,
  "square-check-big": SquareCheckBig,
  star: Star,
  target: Target,
  tent: Tent,
  user: User,
  users: Users,
  video: Video,
  "volume-2": Volume2,
  zap: Zap,
} as const;

export type IconKey = keyof typeof ICONS;
