import {
  Mic,
  Clock,
  Sprout,
  Shield,
  Smile,
  Users,
  AlertCircle,
  Book,
  Zap,
  Circle,
  Target,
  BookOpen,
  Tent,
  MessageCircle,
  Star,
  BarChart,
  PenLine,
  User,
  Handshake,
  Globe,
  Flame,
} from "lucide-react";

export const ICONS = {
  circle: Circle,
  mic: Mic,
  clock: Clock,
  sprout: Sprout,
  shield: Shield,
  smile: Smile,
  users: Users,
  "alert-circle": AlertCircle,
  book: Book,
  zap: Zap,
  target: Target,
  "book-open": BookOpen,
  tent: Tent,
  "message-circle": MessageCircle,
  star: Star,
  "bar-chart": BarChart,
  "pen-line": PenLine,
  user: User,
  handshake: Handshake,
  globe: Globe,
  flame: Flame,
} as const;

export type IconKey = keyof typeof ICONS;
